tabu_search:
  max_iterations: 20000
  tabu_list_size: 20

experiments:
  num_runs: 10
  random_seeds: [42, 123, 456, 789, 101, 202, 303, 404, 505, 606]

output:
  save_results: true
  results_directory: "data/results"
  show_worker_logs_in_parallel: False

visualization:
  save_plots: true
  style: "light" # options are 'light' or 'black'
  plot_formats: ["png"]
