tabu_search:
  tabu_list_size: 40
  max_iterations: 20000

strategies:
  intensification:
    # After how many iterations without improvement to trigger intensification.
    # The algorithm restarts from one of the best solutions found.
    # Set to 0 to disable.
    stagnation_limit: 100
    # Number of elite solutions to keep in memory.
    elite_solutions_count: 5
  
  diversification:
    # After how many iterations without improvement to trigger diversification.
    # The algorithm resets to explore a new area.
    # This limit should be higher than the intensification one.
    # Set to 0 to disable.
    reset_limit: 300

# Long-term frequency memory
frequency:
  enabled: true
  # Penalty factor for frequent moves (0.001 - 0.1)
  # Higher values = more penalty for repeated moves
  alpha: 0.01

# Path relinking between elite solutions
path_relinking:
  enabled: true
  # Iteration interval to check for path relinking
  frequency: 50
  # Probability to perform path relinking when checked
  probability: 0.3
  # Max steps per path relinking session
  max_steps: 10

output:
  results_directory: 'data/results'
  show_worker_logs_in_parallel: false

visualization:
  save_plots: true
  style: 'light'  # options: 'light' or 'dark'

experiments:
  num_runs: 10
  # Random seeds for reproducibility
  random_seeds:
    - 2147483648
    - 1618033988
    - 1732050810
    - 2236067977
    - 2645751311
    - 3141592653
    - 2718281828
    - 1414213562
    - 1000000007
    - 1234567891

# Advanced parameters for fine-tuning
advanced:
  # Threshold to consider two solutions as "different" in path relinking
  solution_distance_threshold: 1
  
  # Flow reduction factor during path relinking
  flow_reduction_factor: 0.5
  
  # Minimum elite solutions required to activate path relinking
  min_elite_for_path_relinking: 2
  
  # Advanced logging
  detailed_logging: false
  
  # Save frequency statistics
  save_frequency_stats: false