tabu_search:
  max_iterations: 20000
  tabu_list_size: 100
  aspiration_enabled: true
  delta_step: 1.0
  intensification_threshold: 50
  diversification_threshold: 100
  elite_size: 5

experiments:
  num_runs: 10
  random_seeds: [42, 123, 456, 789, 101, 202, 303, 404, 505, 606]

output:
  save_results: true
  results_directory: "data/results"

visualization:
  save_plots: true
  plot_formats: ["png"]
  dpi: 150