# Configuration for Maximum Flow Tabu Search Experiments

# Tabu Search Parameters
tabu_search:
  max_iterations: 20000
  tabu_list_size: 20
  aspiration_enabled: true
  delta_step: 1.0
  intensification_threshold: 50
  diversification_threshold: 100
  elite_size: 5

# Experiment Configuration
experiments:
  multiple_runs: true
  num_runs: 10
  random_seeds: [42, 123, 456, 789, 101, 202, 303, 404, 505, 606]

# Visualization Settings
visualization:
  save_plots: true
  show_plots: false
  plot_format: "png"
  figsize: [12, 8]

# Output Configuration
output:
  save_results: true
  verbose: true